version: '3'
services:

  db:
    image: mysql:5.7
    container_name: chatbot_db
    restart: always
    ports:
        - "3306:3306"
    environment:
       - MYSQL_ROOT_PASSWORD=iii
    volumes:
       - ./mysql_data:/var/lib/mysql
       - ./mysql_init:/docker-entrypoint-initdb.d/

  api:
    build:
      context: ./dockerfile
      dockerfile: dockerfile-api2
    container_name: chatbot_api
    restart: always
    user: root
    environment:
       - GRANT_SUDO=yes
    ports:
      - "8880:8888"  
      - "5001:5000"
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./code:/home/jovyan/work/
    command:  start-notebook.sh --NotebookApp.token=''   
